---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config

- name: Install/update plugins
  command: java -jar {{ jenkins.cli_dest }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }} install-plugin {{ item }}
  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1
  with_items: "{{ plugins }}"
  notify:
    - 'Restart Jenkins'
