---

- name: Configure Jenkins Port
  sudo: yes
  when: port is defined
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{port}}

- name: Configure Jenkins Prefix
  sudo: yes
  when: prefix is defined
  lineinfile: dest=/etc/default/jenkins regexp=^PREFIX= line=PREFIX={{prefix}}

- name: Configure Jenkins E-mail
  sudo: yes
  when: email is defined
  template: src=hudson.tasks.Mailer.xml.j2 dest={{ jenkins_lib }}/hudson.tasks.Mailer.xml owner=jenkins group=jenkins mode=0644

- name: Enable ufw
  ufw: state=enabled policy=allow

- name: Disable default in
  ufw: direction=incoming policy=deny

- name: Allow ssh in
  ufw: rule=limit name=OpenSSH

- name: 8080 is open
  ufw: rule=allow port=8080 proto=tcp

- name: Ensure jenkins_dest {{ jenkins_dest }} exists
  file:
    path: "{{ jenkins_dest }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true
