---
- name: Add repository for OpenJDK 8 (Ubuntu 14).
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Set the java_packages variable (Ubuntu).
  set_fact:
    java_packages:
      - openjdk-8-jdk
  when: ansible_distribution == 'Ubuntu'

- name: Install Java
  apt:
    name: "{{ java_packages }}"

- name: Ensure dependencies are installed.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python-apt
      - curl
      - gnupg2
      - gnupg-agent
      - apt-transport-https

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ __jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ __jenkins_repo_url }}"
    state: present
    update_cache: true

- name: Download specific Jenkins version.
  get_url:
    url: "{{ __jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  register: specific_version
  when: jenkins_version is defined

- name: Install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  when: jenkins_version is defined and specific_version.stat.exists
  notify: configure default users

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: present
  notify: configure default users
