---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  deb:
    repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
    dependencies: 
      - 'git'
      - 'curl'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' 
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json'
