---
- name: Converge
  hosts: all

  vars:
    jenkins_url_prefix: /jenkins

  roles:
    - role: jenkins

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8181/"

    - name: Ensure Jenkins is running with the specified prefix.
      uri:
        url: "http://127.0.0.1:8181{{ jenkins_url_prefix }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
